# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='buddy',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
