# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0002_auto_20170628_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buddy', models.ManyToManyField(related_name='trips', to='travel_buddy_app.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates', to='travel_buddy_app.User')),
            ],
        ),
    ]
